#cloud-config

hostname: debian-rdp
manage_etc_hosts: true

users:
  - name: admin
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    plain_text_passwd: "GantiPasswordKuat123"

package_update: true
package_upgrade: true

packages:
  - xfce4
  - xfce4-goodies
  - xrdp
  - dbus-x11
  - xorg
  - sudo
  - wget
  - curl
  - chromium

timezone: Asia/Makassar

runcmd:
  # set XFCE sebagai default session RDP
  - echo xfce4-session > /home/admin/.xsession
  - chown admin:admin /home/admin/.xsession

  # enable XRDP
  - systemctl enable xrdp
  - systemctl restart xrdp

  # firewall RDP
  - ufw allow 3389/tcp || true

  # optimasi ringan untuk XFCE session
  - sudo -u admin mkdir -p /home/admin/.config

final_message: "Debian RDP + XFCE + Chromium siap digunakan (port 3389)"
